name: Build/release

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --global yarn
      - run: yarn
      - run: yarn make

      - name: See inside
        run: cd out/make/deb/x64 && ls

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            out/**/*.deb
            out/**/*Setup.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
